### ISSUE TITLE
My head

### ISSUE THREAD

**Issue by mirkan1** [omerbselvi/Space-Shooter#1]
I want my head as a selectable space ship 👍 
https://i.hizliresim.com/Q2myQk.jpg

**Comment by omerbselvi** [comment]
Will do for sure in the next update. 👍

**Comment by omerbselvi** [comment]
DONE https://github.com/omerbselvi/Space-Shooter/commit/c3c01690604002f8a0a649279303b9fa08f87cdd#diff-8f6856f74b38f25a2cd512d323faae48
